public enum TipoToken {
    INT, FLOAT, DOUBLE, CHAR, BOOLEAN, STRUCT, IF, ELSE, WHILE, FOR, SWITCH, CASE, DEFAULT, BREAK, CONTINUE, RETURN,
    
    ATRIBUICAO, SOMA, SUBTRACAO, MULTIPLICACAO, DIVISAO, MODULO, INCREMENTO, DECREMENTO,
    MAIOR, MAIOR_IGUAL, MENOR, MENOR_IGUAL, IGUALDADE, DIFERENCA, AND, OR, NOT,
    
    PONTO_VIRGULA, VIRGULA, ABRE_PARENTESES, FECHA_PARENTESES, ABRE_CHAVES, FECHA_CHAVES, ABRE_COLCHETES, FECHA_COLCHETES,
    
    IDENTIFICADOR, NUMERO_INTEIRO, NUMERO_DECIMAL, TEXTO,
    
    COMENTARIO, FIM_ARQUIVO, PALAVRA_RESERVADA, SIMBOLO_ESPECIAL, OPERADOR
}